version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password123
      - N8N_ENCRYPTION_KEY=XckaKa/NvIkCdZ0PGkDXI94DWIjFiy/z
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_CREDENTIALS_OVERWRITE_ENDPOINT=credentials
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC
      - N8N_RESTRICTED_MODE=false
      - N8N_DISABLE_UI_ACCESS=false
    restart: unless-stopped
